### PR TITLE
Adds support for JC3248W535EN

### PR DESCRIPTION
**Pull request by i-am-shodan**
https://www.aliexpress.com/item/1005007566332450.html

* Support for axs15231b LCD
* Support for 1bit SD card access
* Enabled better access for shared lvgl thread for panels where other work needs to be performed

### CODE REVIEW

**Comment by Spooks4576** [comment]
thank you for this if i have any more issues with this code i will let you know

**Comment by i-am-shodan** [comment]
Thanks for merging. I've got another PR I'm working on that improves the UI for this device a bit. Just working out how to integrate it cleanly.

**Comment by Spooks4576** [comment]
> Thanks for merging. I've got another PR I'm working on that improves the UI for this device a bit. Just working out how to integrate it cleanly.

Currently fixing up your changes as it broke pretty much every other board thats not yours so yeah 
i got everything to compile except on the CYD im testing its just a white screen so im not sure what you changed but im looking into it

**Comment by Spooks4576** [comment]
Fixed on development branch

**Pull request merged**
