### PR TITLE
add control app using qt6

### PR DESCRIPTION
**Pull request by 1999AZZAR**
add a GUI app to control the ghost esp (the esp standalone ver) tobe used at ease

### CODE REVIEW

**Comment by Spooks4576** [comment]
thank you for making this I will see if I can fit this into the repo somehow soon

**Comment by 1999AZZAR** [comment]
You're welcome! and maybe In the next few days, I should have a new version ready that’s more refined and includes all available commands from `command.md`.

**Comment by Spooks4576** [comment]
can you do me a favor before i upload this 

can you make sure you have a readme guide on how to use this for the people that don't have python installed 

thanks

**Comment by Spooks4576** [comment]
ill merge this soon in the mean time can you maybe put it in the scripts folder in a subfolder of the name of this utility 

thank you

**Comment by Spooks4576** [comment]
> Alright, I’ll follow your suggestion. If you’re able, could you also add some extra serial functions, like saving settings or displaying ASCII art? It would help me make a more complete control app for the ESP module.

this will come in future versions right now this firmware is still very much in Alpha hence the A in the versions

**Pull request merged**
